planner_frequency: 3
recovery_behavior_enabled: true

TrajectoryPlannerROS:
  max_vel_x: 0.319
  min_vel_x: 0.079
  max_vel_theta: 1.5
  min_vel_theta: -1
  min_in_place_vel_theta: 0.05
  escape_vel: -0.1064
  

  acc_lim_theta: 1.5
  acc_lim_x: 0.5
  acc_lim_y: 0.5
  
 

  holonomic_robot: false







 
